### PR TITLE
fix for write UDP: Operation not permitted (code=1)

### PR DESCRIPTION
**Pull request by wivaku**
see workaround mentioned in:
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/59#issuecomment-1046047073

And (hopefully) issues:
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/34
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/38
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/41
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/60
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/71
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/81
https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/94

### CODE REVIEW

**Comment by guillaumedsde** [comment]
Hi, thanks for the contribution and sorry for the late reply, could you change the PR to merge into the development branch and rebase/merge development into it?

**Comment by guillaumedsde** [comment]
Hi, thanks for the contribution and sorry for the late reply, could you change the PR to merge into the development branch and rebase/merge development into it?

**Comment by wivaku** [comment]
not sure how to do that.

**Comment by guillaumedsde** [comment]
Replaced by https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/pull/131

**Pull request closed without merging**
